name: CI Pipeline
on: [pull_request, push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      # Create minimal .golangci.yml if none exists
      - name: Setup lint configuration
        run: |
          if [ ! -f .golangci.yml ]; then
            echo 'run: {timeout: 3m}' > .golangci.yml
          fi

      # Run linter with fallback configuration
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=3m --skip-dirs-use-default

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build -o myapp .