name: CI Pipeline
on: [pull_request, push]  # Triggers on both PRs and direct pushes

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - uses: actions/checkout@v4

      # 2. Set up Go
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true  # Enable dependency caching for faster runs

      # 3. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 4. Run golangci-lint (popular Go linter aggregator)
      - name: Install and run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          golangci-lint run --timeout 3m


      # 6. Build the binary
      - name: Build
        run: go build -o myapp .
