name: CI Pipeline
on:
  [pull_request, push]
jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: check linter to run
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6