name: CI Pipeline
on: [pull_request, push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Solution 1: Generate go.sum first
      - name: Generate dependencies
        run: go mod tidy

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true  # Now this will work

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=3m

      - run: go mod download
      - run: go test -v ./...
      - run: go build -o myapp .